### ISSUE TITLE
Redis Clients page C# link goes to wrong section

### ISSUE THREAD

**Issue by Assisting** [redis/redis-io#182] opened 2019-10-15 15:27 UTC
Repro:

1. Go [here](https://redis.io/clients)
2. Click "C#"
3. Browser directs user toward C section

I'll submit a PR with a fix shortly. 😉

**Comment by itamarhaber** [comment] 2019-10-16 23:02
Looks relate to #134 and https://github.com/antirez/redis-doc/pull/1087. Definitely needs resolution.

**Comment by Assisting** [comment] 2019-10-17 00:31
Oh, whoops, I didn't look hard enough for other PRs. Mine has the advantage of not changing the text being displayed but honestly either one would be perfectly clear.

**Comment by itamarhaber** [comment] 2019-10-17 13:25
@Assisting I agree, yours deals with the root cause and the other just with the symptom.

**Comment by itamarhaber** [comment] 2020-11-08 16:07
Closed via #220

**Closed by itamarhaber** 2020-11-08 16:07 UTC
